### PR TITLE
Updates for view overrides

### PR DESCRIPTION
**Pull request by fordmadox**

### CODE REVIEW

**Comment by ucancallmealicia** [comment]
I didn't test this out on my local instance, but I assume Mark did so it's all good :)

**Review by ucancallmealicia — COMMENTED** [review]
So is this change just the newline and then some fixes to indentation?

**Comment by fordmadox** [comment]
@ucancallmealicia yeah, sorry I meant to mention that we've had that in TEST for a while:  https://github.com/YaleArchivesSpace/aspace-deployment/commit/3635208530606d48dc159f70b031d293d3d8b407#diff-9e0c193416ae2b5cf89f1fa200291c59

**Comment by fordmadox** [comment]
the only changes were me adding back in some stuff that was already in one of our view overrides.  just a bunch of regex replacements for name/title entries, where we stuff those MARC subfield codes into ASpace's qualifier field:  https://github.com/YaleArchivesSpace/display_multiple_containers/pull/2/commits/addf133ac90eedb68aab6028f4b9962096c8e8f3.

**Pull request merged**
